# GXII-LFEX プリセット設定: 標準
# 一般的なGXII-LFEX実験に適した設定

analysis:
  gx_region:
    xmin: 520
    xmax: 600
    ymin: 4
    ymax: 1020
  lfex_region:
    xmin: 700
    xmax: 800
  processing:
    noise_threshold: 0.1
    smoothing_window: 5
    prominence: 0.1
    ma_window: 20
    peak_threshold: 0.1

time_calibration:
  mode: "全幅指定"
  full_width_time: 4.8
  pixel_count: 1024
  time_per_pixel: 0.004688
