analysis:
  gx_region:
    xmax: 600
    xmin: 520
    ymax: 1020
    ymin: 4
  lfex_region:
    xmax: 800
    xmin: 700
  processing:
    ma_window: 20
    noise_threshold: 0.1
    peak_threshold: 0.1
    prominence: 0.1
    smoothing_window: 5
app:
  debug_mode: false
  description: GXII-LFEX実験のタイミング解析GUI
  name: GXII-LFEX Timing Analysis GUI
  version: 1.9.0
files:
  img_settings:
    byte_order: little
    default_dtype: uint16
    default_height: 1024
    default_width: 1024
  output_dir: output
  supported_formats:
  - .txt
  - .csv
  - .dat
  - .img
  temp_dir: temp
gui:
  layout: wide
  page_icon: 🔬
  page_title: GXII-LFEX Timing Analysis
  port_range:
  - 8501
  - 8510
  sidebar_state: expanded
logging:
  format: '[%(asctime)s] %(levelname)-8s - %(name)s: %(message)s'
  handlers:
    console:
      enabled: true
      level: INFO
    file:
      backup_count: 5
      enabled: true
      filepath: logs/app.log
      level: DEBUG
      max_size: 10MB
    gui:
      enabled: true
      level: INFO
      max_lines: 1000
  level: INFO
plot:
  colors:
    gxii: '#2ca02c'
    lfex: '#1f77b4'
    peak: '#d62728'
    primary: '#1f77b4'
    secondary: '#ff7f0e'
    success: '#2ca02c'
    warning: '#d62728'
  dpi: 100
  figure_size:
  - 12
  - 8
  line_width: 2
  marker_size: 6
reference_time:
  absolute_value: 0.0
  labels:
    absolute: Absolute Time (ns)
    custom_t0: Custom Waveform t0 (ns)
    gxii_peak: Relative Time from GXII Peak (ns)
    gxii_rise: Relative Time from GXII Rise (ns)
    lfex_peak: Relative Time from LFEX Peak (ns)
    manual: Relative Time from Reference (ns)
  manual_value: 0.0
  mode: gxii_peak
time_calibration:
  full_width_time: 4.8
  mode: 全幅指定
  pixel_count: 1024
  time_per_pixel: 0.004688
waveform:
  custom_pulse:
    enabled: false
    file_path: ''
    preprocessing:
      interpolation_factor: 10
      normalize: true
      smoothing_window: 3
  fitting:
    fallback_to_maximum: true
    initial_guess_method: auto
    max_iterations: 1000
    tolerance: 1e-8
  gaussian:
    fixed_sigma: 0.553
    fwhm: 1.3
    method: fixed_pulse
  type: gaussian
xsc_summary:
  annotations:
    font_size: 10
    show_parameters: true
    show_peaks: true
    show_regions: true
  panels:
    include_annotation_box: true
    include_processed_image: true
    include_raw_image: true
    include_space_lineout: true
    include_time_lineout: true
    layout: 5_panel
  pdf:
    annotation_level: 詳細
    default_colormap: viridis
    default_dpi: 300
    include_metadata: true
    page_format: A4_landscape
